### PR TITLE
Refactor the Architecture towards reusability and scalability, fix the Monorepo structure

### PR DESCRIPTION
**Pull request by achimcc**
I investigated the Apps architecture and I think it is great that it uses a monorepo structure and has an Architecture pattern. But currently the local Yarn workspace are not correctly configured. This is how the Apps monorepo structure currently looks like:

canvas-ui-dep-graph-original

I fixed the broken local dependencies in each sub-repo. This is how the apps architecture looks like after resolving the local dependencies:

canvas-ui-dependencies

Here, the black arrows are indicating some cyclic references. I figured out that the App is using two different stores, one for managing things like Session Data and one for the Smart Contract related data. 

I suggest to isolate the second store into its own package. Then I would try to make the lower layers like api, signer, hooks, query as agnostic as possible from the store. This would allow for a better reusability, composability and testability of the App. I already started with isolating the store.

This is the current architecture after isolating the store:

canvas-ui-full-deps-isolated-store

I suggest to rename the `store` to `contractStore` in a next step, as well as  trying to decouple the lower layers from the store, so that it sits around the other @canvas-ui/apps-*** repo's. I will try to make a second commit with an overall cleaner structure within the next few days.

### CODE REVIEW

**Comment by achimcc** [comment]
Can still be improved and not everything regarding the monorepo structure is fixed, but I think that the cyclic dependencies are gone with my last commit :)

updated-architecture

**Comment by Robbepop** [comment]
Since this is originally a fork of Polkadot JS Apps it might be interesting for @jacogr to review.

**Comment by jacogr** [comment]
Sorry, have to decline - have enough on my plate so really don't have the time to look at other projects that has no feedback loop into polkadot-js, nor any effect on it. The reviews from external contributors keeps me busy enough as it is in the polkadot-js sphere.

I would however appreciate if this stops ripping off the code and losing the original copyright headers. Apache 2 means you can do what you like (which is the intent), however you at least need to provide attribution to the original.

**Comment by Robbepop** [comment]
> Sorry, have to decline - have enough on my plate so really don't have the time to look at other projects that has no feedback loop into polkadot-js, nor any effect on it. The reviews from external contributors keeps me busy enough as it is in the polkadot-js sphere.
> 
> I would however appreciate if this stops ripping off the code and losing the original copyright headers. Apache 2 means you can do what you like (which is the intent), however you at least need to provide attribution to the original.

I was not aware that this was happening but be assured that this will stop immediately.

**Comment by kwingram25** [comment]
Thank you for this - will review!

**Comment by achimcc** [comment]
> Thank you for this - will review!

No worries! I enjoyed working with it, but I'm also new to monorepos. However, from my experiences with other achitectures, I think it is a good idea to separate the modules and avoid circular dependencies.

Please consider this only as a suggestion. I did it really fast, not very rigorous and I think I could do it much better and cleaner if I take some time to learn more about the underlying components first. 

And at the current stage, there are still some circular dependencies in the app, and the @canvas-ui/react-api part should certainly move further down in the architecture, i.e. shouldn't consume other modules.

**Comment by kwingram25** [comment]
There are way more changes than I can look at because of your linting cleanups. Can you simplify it back to the dependency changes only?

**Comment by achimcc** [comment]
> There are way more changes than I can look at because of your linting cleanups. Can you simplify it back to the dependency changes only? The included .eslintrc should work for you

I tried, but it didn't format it correctly. I will find a way to fix the formatting. I just want to finish the refactoring first, but its nearly done. Here is how it currently looks like:

canvas-ui-dep-graph

There are only some circular dep's between

react-components <-> react-query

and

react-components <-> react-params

remaining.

**Comment by achimcc** [comment]
The problem there was, that react-components contains the basic components like buttons, inputs... While react-query and react-params are containing more app specific components. Therefore react-components has a much higher reusability among other apps then the two others and therefore shouldn't consume them.

My last commit compiles and executes and this is the apps architecture without circular dependencies:

canvas-ui-dep-graph

However, I think that there are a lot of details which need to be fixed...

**Comment by Robbepop** [comment]
Sorry, no JS dev here but what are there and why are they checked in?
2021-02-11-111432_2122x688_scrot

**Comment by achimcc** [comment]
> Sorry, no JS dev here but what are there and why are they checked in?
> 2021-02-11-111432_2122x688_scrot

Thanks for the hint! I didn't touch the .gitignore file so far, they are checked in since .yarn is included there, except for releases and plugins subfolders: 

```
// ./gitignore:
...
.yarn/*
!.yarn/releases
!.yarn/plugins
...
```

yarn-sources.js is the yarn source-code, I guess and plugin-interactive-tools some plugin used by yarn. Actually, I don't know why those to subfolders are included in the .gitignore, but I think we can remove them @kwingram25 ?

**Comment by kwingram25** [comment]
I think it would be best if you checked out a new branch from master and apply only the architectural and dependency changes - it's impossible to review this one with every file having unrelated linting changes.

**Comment by achimcc** [comment]
> I think it would be best if you checked out a new branch from master and apply only the architectural and dependency changes - it's impossible to review this one with every file having unrelated linting changes.

Yes, I agree! I will re-apply all changes which I made to a freshly checked out branch! I should find some time for it this week. I promise that I will disable prettier next time before I start working on it ;)

**Comment by statictype** [comment]
Hi @achimcc ! I am Andreea, new JS dev at Parity. 

First of all, you are proposing a massive refactoring with unclear impact on an untested codebase. Apart from that, you have included unrelated changes in this PR, making things really hard to review.
I just started and still figuring how things work around here, so it would be really helpful if you could explain your thought process a bit more. I have a few questions about that:

1. "Yarn workspaces are not correctly configured" - why is that exactly?
2. Which tool did you use to generate the diagrams?
3. "This is how the apps architecture looks like after resolving the local dependencies" - how did you resolve them?
4.  I don't have much experience with monorepos, but i think circular dependencies are not that big of a deal in this context, what do you think?

**Comment by achimcc** [comment]
> Hi @achimcc ! I am Andreea, new JS dev at Parity.
> 
> First of all, you are proposing a massive refactoring with unclear impact on an untested codebase. Apart from that, you have included unrelated changes in this PR, making things really hard to review.
> I just started and still figuring how things work around here, so it would be really helpful if you could explain your thought process a bit more. I have a few questions about that:
> 
> 1. "Yarn workspaces are not correctly configured" - why is that exactly?
> 2. Which tool did you use to generate the diagrams?
> 3. "This is how the apps architecture looks like after resolving the local dependencies" - how did you resolve them?
> 4. I don't have much experience with monorepos, but i think circular dependencies are not that big of a deal in this context, what do you think?

Hi Andreea!

Thanks for your questions! 

*** 1. & 2.: I used two tools: 

- https://www.npmjs.com/package/package-dependency-graph for plotting the graph/architecture
and:
- https://www.npmjs.com/package/depcheck to find missing (or unused) dependencies in the local sub-repos

If you cd into any local rep (e.g. /packages/apps) and run depcheck, it lists al missing or unused dep's of the spedific sub-repo.

So to plot the very first graph, run the following in the main project directory:

```
npm install -g package-dependency-graph
package-dependency-graph --exclude-node_modules --png canvas-ui-dep-graph.png
```


*** 3: Cd into each sub-repo (folder under /packages/*), running depcheck and adding any missing dep's regarding @canvas-ui/*

*** 4: Well, I don't have a lot of experiences with them neither, but I would highly recommend to avoid circular dependencies at all. If you want to write tests, let's say for `@canvas-ui/react-components`, you probably don't want them to break, when you touch something in some layer above it.  

And you want to be able to locate the bug, starting with the specific component in which it appears without considering side-effects from the layers above. If you re-use `@canvas-ui/react-components` for you next project, you probably don't want to include all the more app specific repo's. 

And then there are repo's which admit more of a operational behaviour like `react-api` or `react-hooks`, carrying business logic, and I think it doesn't make sense, that they reference layers which are managing the view or the orchestration of the app.  But I will spend more time thinking about it and I'm open for further discussions around it org architectural questions in general!

Last, I would be highly interested to know if there is any tools which automates this procedure of refactoring and which can be run on a React/TypeScript project, because I think it can be done by an algorithm. Otherwise it might be a nice thing to develop...

**Comment by achimcc** [comment]
@statictype And let me add that I'm aware of the flaws and I'm sorry for them. I did it way too fast and unfortunately didn't disable prettier from the beginning, messing things up. I think I find some time this Friday to redo all changes on freshly checked out branch.

**Pull request closed without merging**
