### PR TITLE
Remove cyclic dependencies from Yarn monorepo

### PR DESCRIPTION
**Pull request by achimcc**
I've redone the changes regarding the cyclic dependencies in the canvas-ui App.

I've only applied changes regarding the @canvas-ui/* dependencies so far. This version is free of cyclic dependencies, but I'll take a second look the next days on possible bugs and other improvements.

This time I decided to keep some files in app-config instead of react-api, so that app-config sits at the bottom of the architecture.

canvas-ui-dep-graph

### CODE REVIEW

**Comment by achimcc** [comment]
I renamed page-contracts module into react-store module, it is just the more meaningful name.

**Comment by kwingram25** [comment]
Thanks for this! Much easier to see what is happening.

Just wanted to ask, what is the rationale for doing this vs. leaving it as is? I think a lot of this is organized in a way that makes more sense and not opposed at all, but curious to know if there are any ill effects. I understand that it technically is not arranged correctly and yarn is smart enough to patch over bad dependencies, but does that have any significant impact on building or performance?

**Comment by achimcc** [comment]
> Thanks for this! Much easier to see what is happening.
> 
> Just wanted to ask, what is the rationale for doing this vs. leaving it as is? I think a lot of your PR is better organized and I am happy to merge once I review it all, but just curious to know if there are any ill effects from the original setup. I understand that it technically is not arranged correctly and yarn is smart enough to work around the flaws, but does that have any significant impact on building or performance?

When Montse asked me to review the repo, I wanted to understand what which part of the app is responsible for. And it just didn't look right to me and I wanted to have this fixed first, before I touch something else. In many programming languages circular dependencies are not allowed and the projects wont compile at all. But I'm just starting to learn Yarn monorepo's for myself. I did some research and found some hints here, that they can be problematic in TypeScript: https://spin.atomicobject.com/2018/06/25/circular-dependencies-javascript/ The Post mentions this circular dependency checker, which could be used together with a commit hook to prevent them in the future. I'm currently trying to construct a monorepo which throws an error or at least produces a performance nightmare, which can be traced back to a cyclic dependency, since I would like to understand this for myself. Will let you know about the results.

**Comment by statictype** [comment]
Hi @achimcc! Thanks for your changes! I have tried to run your branch locally and i ran into some troubles

- i can't see my deployed contracts anymore on the execute page
- when i uploaded a new one i got an infinite loop (tried to reproduce but did not happen again)
- several errors on the deploy page

Screenshot 2021-02-22 at 11 46 50 (2)
Screenshot 2021-02-22 at 11 46 56 (2)
Screenshot 2021-02-22 at 11 48 35 (2)

I agree with you about the architecture needing improvement, but maybe moving files around is not the best solution.
This article describes an interesting solution for circular dependencies. [nasty circular deps](https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de)

I would go even further and suggest Canvas-UI shouldn't be a monorepo. It's an app (leaf level dependency), not a library. No one will import it in their app or depend on it. To have each page of the app as a separate package in a monorepo doesn't make sense to me. Correct me if i'm wrong @kwingram25 

About the missing deps in packages, lerna used to take care of that by running `lerna bootstrap`. Check it out [here](https://github.com/lerna/lerna/tree/main/commands/bootstrap#readme) Now lerna's codebase looks unmaintained, and probably that's why it was removed from canvas-ui (even though i see lerna.json in the project root)
I could not find a Yarn 2 command similar to `lerna bootstrap,` but will keep investigating.

Another thing @achimcc, are you sure the tool you used to plot the dependecy graph understands monorepos? 
I briefly tried  [monorepo mapper](https://www.npmjs.com/package/monorepo-mapper?activeTab=readme ) and looked a bit different from what you have.

**Comment by achimcc** [comment]
Hi @statictype ! Thanks for all the remarks!

I checked for the errors, you are right, there were things broken! Especially some bad typo's in tsconfig, but also some broken ref's for types. I went over it again and I think I fixed most of it. At least I can use the App now and I see my deployed contracts. There still seems to be something wrong with @canvas-ui/Param/Param components which I don't understand now, but I'll check it further later or tomorrow! 

And thanks for the links, they look super interesting and I will think about them and try your dep's checker!

For the monorepo, I'm in favour of this approach, but I agree that it might not be necessary to have an own repo for each page, but it makes sense to me to have repo's for the lower parts of the architecture.

**Comment by statictype** [comment]
Please also rebase on master, i removed some unused files from the codebase today.

**Comment by achimcc** [comment]
Hi pushed some new commits in the morning, this time I deployed a Flipper contract and tested it functionalities and it works! @statictype I'm currently in a train with slow Internet, but I will try to rebase you changes later!
The article that you posted contains an example of a monorepo with cyclic dependencies that lead to an error, thanks! 

I'm still learning details about Lerna and how it is used and how it fits into a setup which is using Yarn workspaces too!

I spent some more time thinking about the benefits of monorepo's and for me they are just a game changer as long as cyclic dendencies are avoided. Let me summarize why:

-In theory, we could reuse some of the packages in other Apps. E.g. the next App might serve a different purpose but it might still deal with Smart Contracts, so we could very easily add the page which is reponsible for uploading smart contracts to it.

But this is not the main point for me: 

-The different pages merely interact with each other and can be tested independently from each other. And if you really want to test all functionalities of the App, it should be much easier to implement this page by page.
-Assume that you want to implement or change some functionality, you will probably do it on one specific page. And then you know, that you have to touch only the files in this specific repo, and you will most likely not break any other functionality, when you touch it.
-When there are components which are shared among different repo's, then as long as you avoid circular dependencies, those components will automatically end up in their own repo in a lower level of the architecture. And usually they do so for a good reason! Assume, that you want to change the overall look and feel of the app, converting from Material-UI to Chakra or whatever, you just have to touch react-components! And one day you might want to migrate from this eventemitter store to Redux or MobX, then you just have to touch react-store.
-Summarizing, I would say that using a monorepo structure while forbidding cyclic dependencies just enforces the usage of Clean Code best practices like [Separation of Concerns](https://medium.com/machine-words/separation-of-concerns-1d735b703a60), High Cohesion and Loose Coupling.

**Comment by achimcc** [comment]
And i tried monorepo mapper, I think I obtain the same dependencies, its just not visualising the hierarchical order?

**Comment by achimcc** [comment]
And i tried monorepo mapper, I think I obtain the same dependencies, its just not visualising the hierarchical order?

Bildschirmfoto 2021-02-23 um 14 59 01

**Comment by statictype** [comment]
> -In theory, we could reuse some of the packages in other Apps. E.g. the next App might serve a different purpose but it might still deal with Smart Contracts, so we could very easily add the page which is reponsible for uploading smart contracts to it.

Smart contracts don't have other uses other than being uploaded to a blockchain, afaik. So reusing any page in another context is improbable. 

All your other arguments and best practices can be applied just fine to a component based architecture. I'm not against the monorepo, i just think that we should unite the pages in an app (with nice clear component architecture). Monorepos, like all other concepts have goods and bads and they're not enforcing anything. It's more about the people and how they use them. :)

The react-components and all other packages in CanvasUI (except the pages) come from here https://github.com/polkadot-js/apps/tree/master/packages
Not sure how your new structure might affect that, i think they are pulled in from time to time. If i understood that correctly then having them as dependecies of the Canvas Ui app makes more sense to me, instead of having a fork.

I think we need another tour @kwingram25 😄

**Comment by kwingram25** [comment]
The react-* packages from apps are intended to eventually be moved to @polkadot-js/ui ([https://github.com/polkadot-js/apps/tree/master/packages/react-api](link)) but not in the near term, so until they will remain forked. They should not be "refreshed" again unless there are breaking changes that require it.

**Comment by achimcc** [comment]
@statictype But would you suggest to keep the folder structure as it is and to just drop the monorepo approach then? Because then, maintaining a nice clear component structure would still mean not to cross import something from one page into another but to put those components into a shared folder? In this case a monorepo, in my oppinion, would "enforce" a better architecture in the way that you can better trace and forbid those circular dependencies. 

Actually I've to admit that I've no experience with a "nice clear component architecture" :)
I was working on one huge monlithic react app in the past which had no architecture at all and where I did some refactoring and came up with a monorepo structure as a solution. And I've worked with other languages, where we always applied a component architecture similar to a monorepo structure.

@kwingram25  So does that mean that I should close this pull-request since I already changed and moved many files between the react-* repos to resolve the cyclic dependencies?

**Comment by achimcc** [comment]
Actually, it looks to me like someone should fix cyclic dep's in polkadot-js first, not in canvas-ui :-/

**Comment by statictype** [comment]
> But would you suggest to keep the folder structure as it is and to just drop the monorepo approach then?

I'm just saying that page-upload, page-deploy and page-execute should be one thing, wether that is an app that consumes other libraries or a package in a monorepo that consumes other packages. Although tbh, I'm not super keen on changing anything architecturally, until i get a better picture of the domain. But these 3 seem like they can't live without each other :)

I never had components that reference each other in my previous projects so far, mostly because we were using this ESlint plugin https://www.npmjs.com/package/eslint-plugin-import

Another thing that i don't understand is why so many packages are skipped from build in Canvas UI? Shouldn't monorepo packages be build individually? Isn't that what makes them reusable? Can we even call this a monorepo? 🤔

**Comment by achimcc** [comment]
Hey @statictype , I tried to rebase on your commit regarding the removal of unused files and I failed. Finally I simply took a look on which files you removed and deleted them in my commit too. Becoming really confident with git on the command line mis something I'm currently focussing on.

I hope its okay to propose this huge change, the current committed version executes without problems on my computer when I upload deploy and execute the flipper contract. But I only opened a pull request because I've been asked to do so and initially probably no one was aware of just how much had to change. But as I wrote earlier, its just a suggestion, and I agree that there is just a lot regarding monorepo's which I didn't fully understand so far and which I (or we) have to learn ;)

**Review by kwingram25 — APPROVED** [review]

**Pull request merged**
